### ISSUE TITLE
Elasticsearch 1.x?

### ISSUE THREAD

**Issue by laneatomic** [etsy/oculus#19]
Oculus looks pretty abandoned, but are there plans to support Elasticsearch 1.x? 0.90.x has been deprecated since October 2014.

**Comment by jonlives** [comment]
@laneatomic Oculus isn't being actively worked on right now, so it's unlikely that ES 1.x support will be added.

In the very near future we'll be updating the Oculus & Skyline repos with project status and what happens moving forward etc - keep an eye on codeascraft.com for more info too :)

**Comment by laneatomic** [comment]
Thanks for the quick response! Any idea when I might look forward to a project update? In the meanwhile, what are you using for metric correlation?

**Comment by jonlives** [comment]
@laneatomic I'm working on the blogpost right now, so hopefully in the next few weeks.

We're not actually using anything for metric correlation right now - we've been working on a toolkit called Thyme which we should be opensourcing this year which gives a bunch of easy-to-use components that let you do all kinds of detections and correlations on metrics.

The general idea is that we can then start looking at solving more discrete problems - we found that the one-size-fits-all approach we took with Skyline and Oculus first time round wasn't actually that useful in practice.

**Comment by laneatomic** [comment]
:+1: Thanks for the update. Looking forward to the blog post and the new project!

**Comment by draco2003** [comment]
interesting reading while you wait:
https://www.usenix.org/sites/default/files/conference/protected-files/srecon15europe_slides_clegg.pdf

**Comment by laneatomic** [comment]
Cool, I'll read through it. We're working on metrics aggregation/alerting at Springleaf right now, hence this discussion. So thank you guys!
